number: 100 # number of log lines to generate

presetFields:
  timestamp:
    begin: # Timestamp of first log line, default is now
    intervalMin: 10 # minimal time interval, as milliseconds
    intervalMax: 10000 # maximal time interval, as milliseconds
  level: [TRACE(5), DEBUG(5), INFO(70), WARN(10), ERROR(5), FATAL(5)]
  pid:
    begin: 1000
    end: 2000
    amount: 1

generators:
  nginxAccess:
    format: flat
    template: '{{printf "%15s" .ipv4}} - - [{{printf "%21s" .timestamp}} 0800] "{{with .weightedHttpRequest}}{{.method}} {{.path}} HTTP/1.1" {{.responseCode}} {{.esponseLength}} "{{.server}}"{{end}} "{{.weightedHttpAgent}}"'
    fields:
      timestamp: {timeFormat: 02/Jan/2006:15:04:05}
  bunyan:
    format: json
    schema:
      time: '{{.timestamp}}'
      level: '{{.app.level}}'
      pid: '{{.app.pid}}'
      v: 0
      id: '{{.app.logger.name}}'
      name: '{{.app.name}}'
      hostname: '{{.app.host.name}}'
      path: '{{.app.logger.file}}'
      msg: '{{.app.logger.message}}'
    fields:
      timestamp: {timeFormat: '2006-01-02T15:04:05.000Z'}
      level: [10(5), 20(5), 30(70), 40(10), 50(5), 60(5)]

apps:
  candidates:
    nginx*4:
      generator: nginxAccess
    apiGateway*2:
      generator: bunyan
      pid: {amount: 2}
      logger:
        candidates:
          dispatcher*3:
            file: dispatch_handler.lua
            message: $randomMessage
          backend*1:
            file: backend_handler.lua
            message: $randomMessage
      host:
        candidates:
          apiw-1: {ip: 192.168.1.11}
          apiw-2: {ip: 192.168.1.12}
    application*6:
      generator: bunyan
      pid:
        begin: 2000
        end: 3000
        amount: 3
      logger:
        candidates:
          OrderController*1:
            file: OrderController.java
            message: $randomMessage
          OrdreService*3:
            file: OrderService.java
            message: $randomMessage
          OrderRepository*6:
            file: OrderRepository.java
            message: $randomMessage
      host:
        candidates:
          app-1: {ip: 192.168.2.11}
          app-2: {ip: 192.168.2.12}
          app-3: {ip: 192.168.2.13}

