timestamp:
  begin: # Timestamp of first log line, default is now
  intervalMin: 10 # minimal time interval, as milliseconds
  intervalMax: 10000 # maximal time interval, as milliseconds

number: 100 # number of log lines to generate

apps:
  - name: nginx
    format: bunyan
    weight: 4
    level:
      weightTrace: 5 # random weight of TRACE level
      weightDebug: 5 # random weight of DEBUG level
      weightInfo: 70 # random weight of INFO level
      weightWarn: 10 # random weight of WARN level
      weightError: 5 # random weight of ERROR level
      weightFatal: 5
    pid:
      begin: 1000 # begin of PID
      end: 2000 # begin of PID
      amount: 2 # amount of PID
    loggers:
      - name: req
        weight: 1
      - name: resp
        weight: 1
  - name: api-gateway
    format: bunyan
    weight: 2
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 2000
      end: 3000
      amount: 2
    loggers:
      - name: dispatcher
        weight: 3
      - name: backend
        weight: 1
  - name: order-app
    format: bunyan
    weight: 6
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 3000
      end: 4000
      amount: 3
    loggers:
      - name: order-controller
        weight: 1
        message: res:/message.default.txt
      - name: order-service
        weight: 3
      - name: order-repository
        weight: 6
  - name: account-app
    format: bunyan
    weight: 8
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 4000
      end: 5000
      amount: 3
    loggers:
      - name: account-controller
        weight: 1
      - name: account-service
        weight: 3
      - name: account-repository
        weight: 6
  - name: pay-app
    format: bunyan
    weight: 3
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 5000
      end: 6000
      amount: 3
    loggers:
      - name: pay-controller
        weight: 1
      - name: pay-service
        weight: 3
      - name: pay-repository
        weight: 6
      - name: pay-gateway
        weight: 10
