timestamp:
  begin: # Timestamp of first log line, default is now
  intervalMin: 10 # minimal time interval, as milliseconds
  intervalMax: 10000 # maximal time interval, as milliseconds

number: 100 # number of log lines to generate

apps:
  - name: nginx
    format: bunyan
    weight: 4
    level:
      weightTrace: 5 # random weight of TRACE level
      weightDebug: 5 # random weight of DEBUG level
      weightInfo: 70 # random weight of INFO level
      weightWarn: 10 # random weight of WARN level
      weightError: 5 # random weight of ERROR level
      weightFatal: 5
    pid:
      begin: 1000 # begin of PID
      end: 2000 # begin of PID
      amount: 2 # amount of PID
    loggers:
      - name: req
        weight: 1
        path: req_handler.c
      - name: resp
        weight: 1
        path: resp_handler.c
    hosts:
      - name: nginx-server-1
        weight: 1
      - name: nginx-server-2
        weight: 1
  - name: api-gateway
    format: bunyan
    weight: 2
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 2000
      end: 3000
      amount: 2
    loggers:
      - name: dispatcher
        weight: 3
        path: dispatch_handler.lua
      - name: backend
        weight: 1
        path: backend_handler.lua
    hosts:
      - name: api-gateway-server-1
        weight: 1
      - name: api-gateway-server-2
        weight: 1
  - name: order-app
    format: bunyan
    weight: 6
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 3000
      end: 4000
      amount: 3
    loggers:
      - name: order-controller
        weight: 1
        message: res:/message.default.txt
        path: OrderControllere.java
      - name: order-service
        weight: 3
        path: OrderService.java
      - name: order-repository
        weight: 6
        path: OrderRepository.java
    hosts:
      - name: order-server-1
        weight: 1
      - name: order-server-2
        weight: 1
      - name: order-server-3
        weight: 1
  - name: account-app
    format: bunyan
    weight: 8
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 4000
      end: 5000
      amount: 3
    loggers:
      - name: account-controller
        weight: 1
        path: AccountController.java
      - name: account-service
        weight: 3
        path: AccountService.java
      - name: account-repository
        weight: 6
        path: AccountRepository.java
    hosts:
      - name: account-server-1
        weight: 1
      - name: account-server-2
        weight: 1
      - name: account-server-3
        weight: 1
  - name: pay-app
    format: bunyan
    weight: 3
    level:
      weightTrace: 5
      weightDebug: 5
      weightInfo: 70
      weightWarn: 10
      weightError: 5
      weightFatal: 5
    pid:
      begin: 5000
      end: 6000
      amount: 3
    loggers:
      - name: pay-controller
        path: PayController.java
        weight: 1
      - name: pay-service
        path: PayService.java
        weight: 3
      - name: pay-repository
        weight: 6
        path: PayRepository.java
      - name: pay-gateway
        path: PayGateway.java
        weight: 10
    hosts:
      - name: pay-server-1
        weight: 1
      - name: pay-server-2
        weight: 1
      - name: pay-server-3
        weight: 1
